# Generated by Django 5.0.2 on 2024-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
