# Generated by Django 4.0.1 on 2024-03-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_tado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tado',
            new_name='Todo',
        ),
    ]
