# Generated by Django 4.0.1 on 2024-03-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='title',
        ),
    ]
