# Generated by Django 4.0.1 on 2024-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_chek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chek',
        ),
        migrations.AddField(
            model_name='todo',
            name='pomodoro',
            field=models.IntegerField(default=1),
        ),
    ]
