# Generated by Django 4.0.1 on 2024-04-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_todo_pomo_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
